name: Github HeartBeat

on:
  schedule: [{cron: "5 1 * * *"}]
  #API trigger for Cloudflare worker
  #repository_dispatch:
  #  types: [daily]
  watch:
    types: [started]
  workflow_dispatch:
jobs:
  heartbeat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sent Heartbeat
        run: |
         curl https://uptime.betterstack.com/api/v1/heartbeat/${{HEARTBEAT_ID}}
        env:
          HEARTBEAT_ID: ${{ secrets.HEARTBEAT_ID }}
