name: Metrics
on:
  # Schedule daily updates
  # schedule: [{cron: "0 0 * * *"}]
  watch:
    types: [started]
  # (optional) Run workflow manually
  workflow_dispatch:
  #API trigger for Cloudflare worker
  repository_dispatch:
    types: [daily]
jobs:
  Metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
            filename: metrics.plugin.isocalendar.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_isocalendar: yes
            plugin_isocalendar_duration: full-year
