name: Metrics-UpdateLess
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 10,20,30 * *"}]
  # (optional) Run workflow manually
  watch:
    types: [started]
  # push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  Metrics-UpdateLess:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Classic
        uses: lowlighter/metrics@latest
        with:
            filename: metrics.classic.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: header, repositories
            plugin_lines: yes
      - name: Compact display
        uses: lowlighter/metrics@036dd758743abe11e8a91b35a13e4a32aa208b87418b6c98812fe6d9f4f132c9
        with:
            filename: metrics.achievements.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_achievements: yes
            plugin_achievements_only: >-
              polyglot, stargazer, maintainer, developer, forker
            plugin_achievements_display: detailed
