name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  watch:
    types: [started]
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
            filename: metrics.plugin.isocalendar.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_isocalendar: yes
            plugin_isocalendar_duration: full-year
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics_licenses.svg
          repo: Experimental-Repo
          template: repository
          base: ''
          plugin_licenses: yes
          plugin_licenses_ratio: yes
          plugin_licenses_legal: yes
