name: Metrics-UpdateLess
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 10,20,30 * *"}]
  # (optional) Run workflow manually
  watch:
    types: [started]
  # push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  Metrics-UpdateLess:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Classic
        uses: lowlighter/metrics@latest
        with:
            filename: metrics.classic.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: header, repositories
            plugin_lines: yes
      - name: Featured repositories
        uses: lowlighter/metrics@latest
        with:
            filename: metrics.repositories.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_repositories: yes
            plugin_repositories_featured: GoodPass,GoodPass-v3,GoodPass-v2
